import '../app/customersApp/app';
import '../app/customersApp/animations/listAnimations';
import '../app/customersApp/directives/wcUnique';
import '../app/customersApp/filters/nameCityStateFilter';
import '../app/customersApp/filters/nameProductFilter';
import '../app/customersApp/services/config';
import '../app/customersApp/services/authService';
import '../app/customersApp/services/httpInterceptors';
import '../app/customersApp/services/customersBreezeService';
import '../app/customersApp/services/customersService';
import '../app/customersApp/services/dataService';
import '../app/customersApp/services/modalService';
import '../app/customersApp/controllers/customers/customerEditController'
import '../app/customersApp/controllers/customers/customerOrdersController';
import '../app/customersApp/controllers/customers/customersController';
import '../app/customersApp/controllers/orders/orderChildController';
import '../app/customersApp/controllers/orders/ordersController';
import '../app/customersApp/controllers/aboutController';
import '../app/customersApp/controllers/navbarController';
import '../app/customersApp/controllers/orders/orderChildController';
import '../app/customersApp/controllers/loginController';

