"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
require("./app/customersApp/app");
require("./app/customersApp/app");
require("./app/customersApp/animations/listAnimations");
require("./app/customersApp/directives/wcUnique");
require("./app/customersApp/filters/nameCityStateFilter");
require("./app/customersApp/filters/nameProductFilter");
require("./app/customersApp/services/config");
require("./app/customersApp/services/authService");
require("./app/customersApp/services/httpInterceptors");
require("./app/customersApp/services/customersBreezeService");
require("./app/customersApp/services/customersService");
require("./app/customersApp/services/dataService");
require("./app/customersApp/services/modalService");
require("./app/customersApp/controllers/customers/customerEditController");
require("./app/customersApp/controllers/customers/customerOrdersController");
require("./app/customersApp/controllers/customers/customersController");
require("./app/customersApp/controllers/orders/orderChildController");
require("./app/customersApp/controllers/orders/ordersController");
require("./app/customersApp/controllers/aboutController");
require("./app/customersApp/controllers/navbarController");
require("./app/customersApp/controllers/orders/orderChildController");
require("./app/customersApp/controllers/loginController");
